name: SurvivalSystem
version: '1'
main: dev.subscripted.survivalsystem.Main
api-version: '1.20'
author: Subscripted
description: Das Novibes.de Survival System verbindet BungeeCord Funktionen mit Bukkit Interaktionen, genauso wie andere Befehle die Nützlich sein könnten.
website: github.com/subscripted
commands:
  tpa:
  tp:
  tpahere:
  tphere:
  tpaaccept:
  tpadeny:
  market:
  bank:
  v:
  vanish:
  spawn:
  setspawn:
  fly:
    permission: survival.fly
  ec:
  gm:
  craft:
  seeinventory:
  r:
  msg:
  clan:

